name: Build Lekhoni Keyboard (Artifact)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create build folder + output file
        run: |
          mkdir build
          echo "Lekhoni Keyboard build success" > build/README.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lekhoni-build
          path: build/
