name: Lekhoni Keyboard Builder

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create build folder
        run: mkdir build

      - name: Create keyboard file
        run: echo Lekhoni Keyboard Successfully Built > build/lekhoni.txt

      - name: Upload build file
        uses: actions/upload-artifact@v4
        with:
          name: Lekhoni-Keyboard
          path: build
